version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  install-and-build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: build
          command: npm run build
  release:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: git configure
          command: |
            git config --global user.name $GITHUB_USERNAME
            git config --global user.email $GITHUB_EMAIL
      - run:
          name: release
          command: npm run release
workflows:
  node-tests:
    jobs:
      - install-and-build
      - release:
          context:
            - gh-release
          requires:
            - install-and-build
