version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  release:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: git configure
          command: |
            git config --global user.name $GITHUB_USERNAME
            git config --global user.email $GITHUB_EMAIL
            git remote rm origin
            git remote add origin https://${CIRCLE_PROJECT_USERNAME}:${GITHUB_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git
            git symbolic-ref HEAD refs/heads/main
            git push --follow-tags --set-upstream origin main
      - run:
          name: install
          command: npm install
      - run:
          name: build
          command: npm run build
      - run:
          name: release
          command: npm run release:ci
workflows:
  node-tests:
    jobs:
      - release:
          filters:
            branches:
              only: main
          context:
            - gh-release
